FROM python:3.12-slim

# Install Linux inspection tools (not available on Windows!)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        file \
        exiftool \
        binutils \
        bsdmainutils \
        coreutils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 5000

CMD ["python", "app.py"]
